[package]
name = "anipara"
version = "0.1.0"
authors = ["Ohjun Kwon <dev@kojandy.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
